package hr.fer.zemris.project.geometry.dash.ai;

/**
 * Remembers all important constants for AI
 * @author Andi Škrgat
 *
 */
public class AIConstants {
	
	/**
	 * Maximum number of generations for genetic algorithm
	 */
	public static int maxGenerations = 500;
	
	/**
	 * Number of action in tree
	 */
	public static int numOfActions = 25;
	
	/**
	 * Maximum number of nodes
	 */
	 public static int maxNumberOfNode = 10; //not used so far
	 
	 /**
	  * Initial depth of tree
	  */
	 public static int initialDepth = 6;
	 
	 /**
	 * Maximum depth of tree
	 */
	public static int maxTreeDepth = 17;
	
	/**
	 * Should be okay
	 */
	public static int treePopulationSize = 50;
	
	/**
	 * We have <code>initialDepth<code> levels(2 to <code>initialDepth<code>) and <code>treePopulationSize</code>
	 * divided by <code>initialDepth</code> is populationSizeOfEachDepth
	 */
	public static int populationSizeOfEachDepth = treePopulationSize / (initialDepth-1);
	
	/**
	 * We have same number of trees generated by full and grow method 
	 */
	public static int populationSizeFullGrow = populationSizeOfEachDepth / 2;
	 

}
